version: '3'

services:
  db:
    image: mysql
    ports:
     - '3308:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=178209
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql

  # backendfinanceiro:
  #   image: backendfinanceiro
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - '8080:8080'
  #   links:
  #     - db
  # front-angular:
  #   image: front-angular
  #   build: ../../financeiro-javagas-angular
  #   ports:
  #     - '80:80'
  #   links:
  #     - backendfinanceiro
